# 7.13:  Look at the .__bases__ attribute of the exception
# class ValueError; see if you can follow the chain of bases
# all the way up to object.



